### ISSUE TITLE
Artur kurwa zjebałeś

### ISSUE THREAD

**Issue by mattroot** [artur9010/korwin.js#4]
Gdzieś jest wuoborach zamiast wyborach.

Spierdoliłeś i chuj.
Napraw kurwa.

**Comment by sjal** [comment]
Myślę, że p. Arturowi nie będzie miło gdy to przeczyta...

**Comment by JuniorJPDJ** [comment]
Dobrze mu tak, niech sie weźmie wreszcie do poprawiania.
Dupe mu trujemy o całą mase takich rzeczy i w dupieeeeee to ma.

**Comment by artur9010** [comment]
> Gdzieś jest wuoborach zamiast wyborach.

Zachęcam do wysłania wspaniałego pull requesta.

**Comment by sjal** [comment]
request Boży

**Comment by PrzemyslawPolrolniczak** [comment]
#5 i cyk kontrybucja ołpensors do CV
